name: flutter_kit
description: A new Flutter package project.
version: 1.0.16
homepage: https://github.com/Sethyrus/flutter_kit

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  collection: any
  easy_localization: ^3.0.5
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.4.10
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^1.0.8
  go_router: ^13.2.0
  graphql: ^5.1.3
  riverpod_annotation: ^2.3.4
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
